### PR TITLE
.github: use common system tests template

### PR DESCRIPTION
**Pull request by evgeniiz321**

### CODE REVIEW

**Comment by roman-khimov** [comment]
Looks like this never ends:

>  run_system_tests Expected — Waiting for status to be reported

**Comment by evgeniiz321** [comment]
@roman-khimov i assume this is because github is waiting for a single job here, and i added a matrix with macos. Need to update the repo settings

**Comment by roman-khimov** [comment]
It allows to add any of subordinate jobs, but also works with top-level.

**Comment by roman-khimov** [comment]
Let's check what's gonna happen after the merge.

**Pull request merged**
