### PR TITLE
Fix/object parts changes

### PR DESCRIPTION
**Pull request by carpawell**

### CODE REVIEW

**Review by roman-khimov — COMMENTED** [review]
Do we have any test for allowed deletions (incomplete objects)?

**Comment by carpawell** [comment]
> Do we have any test for allowed deletions (incomplete objects)?

No. I am not sure if it can be done without additional support in our utils. For now we can only put big object and stop after N seconds?

**Comment by roman-khimov** [comment]
Let's create an issue and think about it separately then.

**Comment by carpawell** [comment]
@roman-khimov, test repo or cli? I agree such a test will be helpful, but do not see any easy solution without some part creation util.

**Comment by roman-khimov** [comment]
Test. We'll untangle from it.

**Review by roman-khimov — APPROVED** [review]

**Review by evgeniiz321 — APPROVED** [review]

**Pull request merged**
